development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      database: organizador_development
      hosts:
        - localhost:27017
      options:
  options:

test:
  clients:
    default:
      database: organizador_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
